version: "3.7"

services:
  app:
    build: .
    init: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

    # for pry-byebug
    stdin_open: true
    tty: true

    environment:
      # webpackのアセットをwebpack-dev-serverから取得する
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - WEBPACKER_DEV_SERVER_PUBLIC=localhost:3035
      # dbコンテナに接続する
      - DATABASE_URL=postgresql://postgres:password@db/calendar_development
    depends_on:
      - db

  webpack:
    build: .
    # Rubyのbinstubを経由してサーバーを実行するようにしている
    command: ruby ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - .:/app
      # node_modulesはイメージにあるものを使う
      - /app/node_modules

  db:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=docker_for_rails_try_and_learn_development
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  # DBの格納先
  db-data:
