version: "3.7"

services:
  app:
    build: .
    init: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

    # for pry-byebug
    stdin_open: true
    tty: true
